name: apj_student_app
description: "APJ Abdul Kalam Welfare Society Student App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.7.0
  firebase_auth: ^5.0.2
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.2

  # Google sign-in
  google_sign_in: ^6.1.5
  
  # Wakelock
  wakelock_plus: ^1.2.11
  image_picker: ^1.0.6
  qr_flutter: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/school_logo.png
    - assets/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700