name: apj_student_app
description: "APJ Abdul Kalam Welfare Society Student App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  cupertino_icons: ^1.0.2

  # Firebase packages
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.2

  # Google sign-in
  google_sign_in: ^5.4.0
  
  # Wakelock
  wakelock_plus: ^1.2.11
  image_picker: ^1.2.1
  qr_flutter: ^4.1.0

  # Shared Preferences
  shared_preferences: ^2.0.15
  http: ^1.6.0
  cloudinary_flutter: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^32.1.21
  url_launcher: ^6.3.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.2.0
  webview_flutter_wkwebview: ^3.1.0
  flutter_pdfview: ^1.4.0+1
  flutter_cached_pdfview: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/school_logo.png
    - assets/images/qr_code.png
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700